### ISSUE TITLE
Colors out of bounds result in weird display

### ISSUE THREAD

**Issue by rFalque** [nmwsharp/polyscope#102]
I had an issue where I used colors for meshes between [0, 255] and the display looked like a Christmas tree (see bellow). It took me some time to understand that I needed to bound the colors between 0 and 1 (which is not directly mentioned in the documentation). It would be nice to have a warning in such a scenario.

For the records, here are the colors in that case:
![Screenshot from 2021-04-09 15-00-36](https://user-images.githubusercontent.com/4261518/114133873-142c2880-994a-11eb-9c96-f1020c8ab38f.png)

**Comment by nmwsharp** [comment]
Hi!

I just added a global clamp to [0,1] in a756380479f8219315cb72cf644320f924c03a55, so the rendering will not look quite so wacky in this case in the future.

Can you point to anywhere this is not mentioned in the docs? It seems to be noted everywhere color quantities are mentioned, but perhaps I'm missing some.

I can see how a helpful hint would be nice here. It should be pretty easy to detect input which is all integers on [0,255] including some >1. My only concern is that I don't want to go too crazy with trying-to-be-helpful warnings which might annoy users automatically visualizing data. Perhaps we could disable all such warnings with a global flag... hmmmm. 

Another option would be have explicit support for colors [0,255]. One of the design principles I try to follow with Polyscope is never requiring users to do any data conversions before passing data in, and right now some users need to divide their colors. We could easily add an additional argument to the color functions, which takes an enum like `ColorRange::ZeroOne` or `ColorRange::Integer256` or something.

**Comment by rFalque** [comment]
Hi Nicholas,

I suppose the bounds of the color should be mentioned on the following pages:
[http://polyscope.run/structures/point_cloud/color_quantities/](http://polyscope.run/structures/point_cloud/color_quantities/)
[http://polyscope.run/structures/surface_mesh/color_quantities/](http://polyscope.run/structures/surface_mesh/color_quantities/)
[http://polyscope.run/structures/curve_network/color_quantities/](http://polyscope.run/structures/curve_network/color_quantities/)

About the warnings, all the ones I have received were actually helpful (there was something wrong with my data which helped for debugging). I suppose you could switch it to be output in the command prompt as an alternative.

I don't really have a strong opinion on supporting Integers. But as a completely different topic, that would be great if `polyscope::init();` could be called several times and managed internally if called multiple time (it currently crash from my previous experience). I currently have to use a flag to make sure I don't call it several times.

**Comment by nmwsharp** [comment]
> I suppose the bounds of the color should be mentioned on the following pages...

It's mentioned on all of those pages, right? If you expand the function block to show the method details: "RGB values are interpreted in the range [0,1]."

> About the warnings, all the ones I have received were actually helpful...

:+1: 

> call init several times

Coincidentally, I made this exact change yesterday! 050538ee90acc3f0beb4e7e4d8232c0f520474ab

**Comment by rFalque** [comment]
Yes, no idea why I did not expand the function block ...

> Coincidentally, I made this exact change yesterday! 050538e

Nice :ok_hand:
