### ISSUE TITLE
addVertexParameterizationQuantity does not account for separated islands

### ISSUE THREAD

**Issue by kabukunz** [nmwsharp/polyscope#104]
Hello there, and thank you for this very neat tool. I have a mesh in libigl format (V,F) with an already calculated parameterization as (TC,FTC). I'd like to do an addVertexParameterizationQuantity so as to show the UV on the whole object. I do the usual `polyscope::registerSurfaceMesh("input mesh", V, F);`then on a callback I do    `polyscope::getSurfaceMesh("input mesh")->addVertexParameterizationQuantity("My parameterization", TC); but when I click on the button I get:

<img width="381" alt="err" src="https://user-images.githubusercontent.com/33091053/115039295-9e3b3a80-9ed0-11eb-87f7-e813bae1039b.png">

"expected 8, has 16" I guess this is because the TC matrix has duplicated vertices as the parameterization separated the object into two islands. To show some figures:

```
==========================================
Vertices (V)  (Rows: 8 Cols: 3)
==========================================
[[        1,        -1,        -1]
 [        1,        -1,         1]
 [       -1,        -1,         1]
 [       -1,        -1,        -1]
 [        1,         1, -0.999999]
 [ 0.999999,         1,  1.000001]
 [       -1,         1,         1]
 [       -1,         1,        -1]]
==========================================

==========================================
Faces (F) (Rows: 12 Cols: 3)
==========================================
[[0, 1, 2]
 [0, 2, 3]
 [4, 7, 6]
 [4, 6, 5]
 [0, 4, 5]
 [0, 5, 1]
 [1, 5, 6]
 [1, 6, 2]
 [2, 6, 7]
 [2, 7, 3]
 [4, 0, 3]
 [4, 3, 7]]
==========================================

==========================================
UV Vertices (TC) (Rows: 16 Cols: 2)
==========================================
[[   1.3614309888764,   0.36367164728237]
 [ 0.361125247419902,   -1.3682026154463]
 [ 0.594732632805677,   1.17650193722438]
 [  2.36183316943265,   2.09543666316544]
 [-0.370418451379585,   1.36405121174654]
 [ -1.37072418219805, -0.367823036926482]
 [ -2.37112674281559,  -2.09958666586288]
 [ 0.630070242450529,   3.09587332243093]
 [  3.20698899005527, 0.0914532647918794]
 [  2.44356483927529,   1.93991494053127]
 [  1.35870258286875, -0.671998163558371]
 [ -2.33681791636096,  -2.20108469407179]
 [ -1.25381870221718,  0.411934430738045]
 [ -3.10184906569348, -0.353302180838706]
 [-0.639364320281127,  -3.10002421514261]
 [-0.489138094945015,  -1.43605381366689]]
==========================================

 ==========================================
UV Faces (FTC) (Rows: 12 Cols: 3)
==========================================
[[ 8,  9,  2]
 [ 8,  2, 10]
 [11, 15, 12]
 [11, 12, 13]
 [ 0,  4,  5]
 [ 0,  5,  1]
 [ 1,  5,  6]
 [ 1,  6, 14]
 [ 2, 12, 15]
 [ 2, 15, 10]
 [ 4,  0,  3]
 [ 4,  3,  7]]
==========================================
```

How do I fix that? I'm new to this tool so maybe I'm getting it wrong...

**Comment by nmwsharp** [comment]
Hi!

As you note, `addVertexParameterization()` really expects one value per vertex, so it's going to complain unless you pass a length-|V| array of texture coordinates in.

As I understand it, the libIGL representation is a set of indices per each corner of each face, which index in to a separate texture array. To use this, you'll want [addCornerParameterizationQuantity()](https://github.com/nmwsharp/polyscope/blob/master/include/polyscope/surface_mesh.h#L108), which expects one texture coordinate per-corner.

However, `addCornerParameterizationQuantity()` still can't quite consume the libIGL data directly, you need to expand out the indirect indexing in to an explicit array with dimensions `Cx2` where `C` is the number of corners in the mesh, so this array actually holds the UV coordinates directly. (I can be more verbose about what I mean there if needed, just let me know)

(by the way, I've also noticed that `addCornerParameterizationQuantity()` is not listed in the docs, creating a separate issue to fix that)

**Comment by nmwsharp** [comment]
Whoops, I can't read, the function name is actually

`addCornerParameterizationQuantity()` --> `addParameterizationQuantity()`

**Comment by kabukunz** [comment]
Ah, sorry, my typo. `addVertexParameterizationQuantity` is what I actually used, as above. I've tried `addParameterizationQuantity` too and i get:

<img width="665" alt="Screenshot 2021-04-17 at 09 45 24" src="https://user-images.githubusercontent.com/33091053/115106003-88765580-9f62-11eb-8e61-42a8604bdde4.png">

as Polyscope is looking for an half-edge structure of 3 x 12 corners...
Basically what I'm trying to do is display a mesh with the usual overimposed checker texture for UV...

**Comment by kabukunz** [comment]
Yes.

<img width="442" alt="Screenshot 2021-04-17 at 18 31 03" src="https://user-images.githubusercontent.com/33091053/115119966-3f96bf00-9fab-11eb-8cdd-e670e8ba590d.png">

closing this as it's not an error. Thanks.
