### ISSUE TITLE
Normalized colormaps

### ISSUE THREAD

**Issue by kabukunz** [nmwsharp/polyscope#110]
I'm trying to implement libigl example 713 in polyscope, and I need to implement a color map programmatically within  a range value like libigl's

`igl::jet(vectorXd input_data, min, max, VectorXd color_output);`

is there a way to do that in polyscope?

**Comment by nmwsharp** [comment]
Hi!

Yes, in Polyscope you can set ranges like:

```cpp
auto psMesh = polyscope::registerSurfaceMesh("mesh", verts, faces);
auto quantity = psMesh->addVertexScalarQuantity("values", myValues);
quantity->setMapRange({lowerLim, upperLim});
```
(pardon any typos)

**Comment by kabukunz** [comment]
Ah, thank you, I see

<img width="482" alt="cutoff" src="https://user-images.githubusercontent.com/33091053/118967741-5db95b80-b96b-11eb-9652-19d9537d8852.png">

the cutoff is shown over the mesh, while the histogram retains the full range of values and shows dimming over the outliers.
Given this flexibility, there's not even the need to set the ranges, sometimes...
Given that Polyscope supports quad meshes, the libigl code just reduces to

```
    if (ImGui::Button("Planarization Level"))
    {
        auto mesh = polyscope::registerSurfaceMesh("mesh", V, F);
        VectorXd angleRegularity(F.rows());
        quadAngleRegularity(V, F, angleRegularity);
        auto quantity = mesh->addFaceScalarQuantity("Planarity", angleRegularity);
        quantity->setMapRange({0.0, 0.05});
    }
```

I really like this tool. So clean.

**Comment by kabukunz** [comment]
forgot to close...
