### ISSUE TITLE
Update pointcloud continuously

### ISSUE THREAD

**Issue by gsp-27** [nmwsharp/polyscope#112]
Hi, I register a point cloud and later in a loop use update point positions to continuously change the positions of the points.

With this setup whenever I use `polyscope::show`, the program gets stuck.

My question is, is there a simple way to view a continuously changing point cloud?

**Comment by nmwsharp** [comment]
Hi!

The best way to continuously update a point cloud is to do so inside of the user callback function, which gets called on every "draw" iteration of the GUI.

This could look something like:
```cpp

polyscope::PointCloud* myCloud;

// Your callback functions
void myCallback() {
   // generate new point cloud values
   auto newPositions = /* ... something ... */;

   // update the positions of the cloud
   myCloud->updatePointPositions(newPositions); 

   // note: if the _number_ of points is changing, you can instead register 
   // a new point cloud in-place of the existing one like
   // myCloud = polyscope::registerPointCloud("cloud", newPositions);
  
}

int main(int argc, char** argv) {

  /*
    ...your program setup...
  */ 

  // Initialize polyscope
  polyscope::init();

  // Specify the callback
  polyscope::state::userCallback = myCallback;

  // Add the point cloud
  myCloud = polyscope::registerPointCloud("cloud", myPoints);

  // Give control to the polyscope gui
  polyscope::show();

  return EXIT_SUCCESS;
}
```

This will quickly update the point cloud once per iteration of the UI.

If necessary, you can wrap the callback in extra logic, such as not doing anything until some button is pressed, etc.

**Comment by gsp-27** [comment]
Thank you!
