### ISSUE TITLE
Is it possible to change the color & transparancy of the slice plane?

### ISSUE THREAD

**Issue by Dong-He** [nmwsharp/polyscope#123]
Hi, the slicing tool of the polyscope is an amazing feature😀 - it can also ignore selected elements to show. I enjoy polyscope and it boosts my visualization work greatly on the path planning.

I would like to change the color & transparency of the slice plane? it is possible to incorporate this feature in the future?

Many thanks!

**Comment by nmwsharp** [comment]
Hi! Glad to hear you're enjoying Polyscope.

Adjusting the appearance of the slice plane does sound useful. I quickly hacked together some options in this 66e0920c7dfff12474d180f66dcd8743fbf125c5 commit, which you can try out now in the `point_render_opts` branch if you're interested. I'll try to get it documented/Python-bound/etc for an upcoming version soon.

**Comment by Dong-He** [comment]
Hi, Thank you very much for the new branch. I have tested it on my machine and it works perfectly.
![image](https://user-images.githubusercontent.com/23613273/134609454-9cabb4f8-c140-4468-ae90-bf1e7ee9e64f.png)
I have recommended polyscope to my labmates, thanks for this amazing tool.
