### ISSUE TITLE
Getting pose of structures from the GUI

### ISSUE THREAD

**Issue by jiviteshjain** [nmwsharp/polyscope#132]
Hi,

After using the Gizmo to set the orientation of a point cloud using the GUI, is there a way I can obtain that pose in the python program after the call to `polyscope.show`? This would be useful in using the GUI to manually fine-tune orientations and then using those values programmatically.

I'm using polyscope 1.2.0 in Python.

**Comment by nmwsharp** [comment]
Hi! It's not possible in 1.2, but I will add python binding for it in 1.3. Hopefuly coming soon :)

FYI on the C++ side we just added much better support for working with transformations in 3b28e0243194b6633de02617100f6f139af65a56

**Comment by nmwsharp** [comment]
Now available in Python here: https://polyscope.run/py/structures/structure_management/#transforms
