### ISSUE TITLE
doc link issue

### ISSUE THREAD

**Issue by xarthurx** [nmwsharp/polyscope#134]
The link for "user callback function" in the page https://polyscope.run/basics/program_options/ under `bool options::openImGuiWindowForUserCallback` was broken.

It points to: https://polyscope.run/basics/user_callback
It should point to: https://polyscope.run/features/user_callback/

It seems the doc is not contained in the repo, so creating an issue here instead of submitting a PR.

**Comment by xarthurx** [comment]
Oh, just found the instruction for doc here: https://polyscope.run/about/contributing/#documentation

But since I'm on Windows and cannot run shell script, I guess this should be a quick fix on your side.

**Comment by nmwsharp** [comment]
Link fixed in https://github.com/nmwsharp/polyscope-docs/commit/201f76622369e50b0719d34dd118986bab72a9b0 . Will update in the public docs next time I rebuild them.

Thanks!
