### ISSUE TITLE
cannot get ImGui info when making customized menu 

### ISSUE THREAD

**Issue by xarthurx** [nmwsharp/polyscope#135]
I disabled `openImGuiWindowForUserCallback` to try to customize my own menu system.
However, functions like `ImGui::GetContentRegionAvailWidth()` reports `nullptr` for `window` and doesn't function correctly.

Refering to https://github.com/nmwsharp/polyscope/issues/133, I think the UI mechanism might need some design or doc to allow more customization for diversified UI looking.

Additionally, it seems when disabling `openImGuiWindowForUserCallback`, the `callback()` function is still activated, titled `debug`, but just not snap to the top right corner.
![image](https://user-images.githubusercontent.com/1921878/140044086-237b8b5e-627d-4ead-9999-0d755c8e0257.png)

**Comment by xarthurx** [comment]
Also tried to use a menuWidget derived from `polyscope::Widget` class to build the GUI, but in vain. 
Not sure how the `Widget` system was supposed to be used.

**Comment by nmwsharp** [comment]
I couldn't reproduce this on my end, can you confirm?

I believe that the `Debug` window is what ImGui does if you start issuing commands without calling `Begin()` to open a window first. Perhaps you disabled `openImGuiWindowForUserCallback`, but then issued some ImGui commands in your callback without calling `Begin()` first?

**Comment by nmwsharp** [comment]
The `Widget` class was meant intended objects that sit in the 3D scene but are not a structure or quantity, such as the transform gizmo (pictured below) or the slice planes. You miiiight be able to customize to create your own UI elements, but it wasn't really designed with that in mind. Feel free to post again if this is something you still want to pursue.

<img width="297" alt="Screen Shot 2021-11-09 at 6 38 03 PM" src="https://user-images.githubusercontent.com/12726725/141022920-54dc26ff-fdb1-4313-ba34-bc4c9e415363.png">

**Comment by nmwsharp** [comment]
Related to this (and your other issues/PRs), I did just push a small commit 7fa7fe6 which adds an option `buildGui` to totally disable all of the Polyscope UIs. This could be useful if someone wanted to build a fancy UI totally from scratch, though I don't know if that fits your use-case.

**Comment by xarthurx** [comment]
> I couldn't reproduce this on my end, can you confirm?
> 
> I believe that the `Debug` window is what ImGui does if you start issuing commands without calling `Begin()` to open a window first. Perhaps you disabled `openImGuiWindowForUserCallback`, but then issued some ImGui commands in your callback without calling `Begin()` first?

Yes, I guess so. My bad.
I'll check the `buidGui` and this is exactly sth I need, thanks!
