### ISSUE TITLE
X axis flipped on planar navigation style

### ISSUE THREAD

**Issue by sgsellan** [nmwsharp/polyscope#144]
I am a big fan of this package. Here's an issue I found:

**Steps to reproduce:**

Run the following MWE:
```
V = np.array([[0., 0.], [1., 0.], [0., 1.], [1., 1.]])
F = np.array([[0, 3, 2], [0, 1, 3]],dtype=int)
ps.init()
ps.register_surface_mesh("my mesh", V , F, smooth_shade=False)
ps_cloud = ps.register_point_cloud("points", np.array([[0.75,0.75]]))
ps.set_navigation_style("planar")
ps.show()
```

**Expected Behaviour:** A Polyscope window opens showing a square and a point in the top right of the square

**Observed behaviour:** A Polyscope window opens showing a square and a point in the top *left* of the square (see below)

<img width="1270" alt="Screen Shot 2021-11-24 at 3 40 39 PM" src="https://user-images.githubusercontent.com/30415788/143328558-632c1495-61dc-4c5e-aab1-ccbcb6a9d4e3.png">

Seems like instead of the traditional cartesian axes with X<0 being on the left and X>0 being on the right, the horizontal axis is inverted and negative X values appear on the right, with positive ones appearing on the left. The Y axis has no such issue (positive is top, negative is bottom).

**Comment by nmwsharp** [comment]
Thanks for the bug report!

This should be fixed on the C++ side in 49256eb. The update will percolate to Python when the next version of the bindings are released.
