### ISSUE TITLE
Set home view to 180 degree rotation from default?

### ISSUE THREAD

**Issue by alecjacobson** [nmwsharp/polyscope#148]
I know that I can set the camera view lookat, but then I have to figure out the center position etc. etc. I like that the home view is data dependent and has a natural default. Unfortunately, most of the models I have are facing backward. Is there an easy way to set the home view to have the z-axis pointing the other way? (rotate by 180 around Y)

libigl vs polyscope on libigl/tests/data/bunny.off
![image](https://user-images.githubusercontent.com/2241689/147170633-0296f373-7f76-4847-9c48-b956fb4b5be3.png)

**Comment by nmwsharp** [comment]
Hmmmm good question. There's not really any easier way to do this now. And in particular, there's nothing that would "persist" in the sense that it would take you back to the view you've selected if you e.g. clicked `Reset View`.

Perhaps we could add a config setting much like up direction `Z_up` setting, there could be a corresponding `forwardDir` choice?

**Comment by nmwsharp** [comment]
The view matrix is a `glm::mat4` at `polyscope::view::viewMat`, you could always just multiply it by a rotation matrix at startup or something or something.

There is some logic that lazily waits to initialize the view matrix until there is some data in the scene, so I thiiiiiink you want to call `polyscope::view::ensureViewValid()` before messing with the view matrix.

**Comment by alecjacobson** [comment]
thanks. I'll try that for now.

**Comment by nmwsharp** [comment]
There is now a `polyscope::view::frontDir` variable which sets the default front viewing direction, and as of commit da965d3 the default is changed to `ZFront` as mentioned above. Thanks for filing the issue!
