### ISSUE TITLE
python - glfw invalid window size

### ISSUE THREAD

**Issue by oracle3001** [nmwsharp/polyscope#154]
Using python, I was using polyscope with no issues. Then all of a sudden anything I try to run ps.init() I get the following error,

GLFW emitted error: Invalid window size 0x1
GLFW emitted error: Cannot set swap interval without a current OpenGL or OpenGL ES context

I have tried uninstalling and reinstalling the package in python, but that doesn't seem to fix it.

Edit:- Fixed it by deleting the .polyscope.ini file. Bit strange how it got in a mess.

**Comment by nmwsharp** [comment]
Ok, I pushed a6b7ecfaf96c101d35c92bbe90f3c6da489d8dd3 to hopefully prevent this.

Please reopen if you are still seeing this issue!
