### ISSUE TITLE
build issue on for some linux/gcc

### ISSUE THREAD

**Issue by dcoeurjo** [nmwsharp/polyscope#18]
Polyscope does not build with the default c++ compiler of  linux/ubuntu OS.

The Pull-request  https://github.com/nmwsharp/geometry-central/pull/7) of geometry-central fixes the issues. Could you please update the submodule version when the GC PR gets merged?

**Comment by nmwsharp** [comment]
Will do this soon-- need to sit down with multiple compilers in front of me to make everything happy cross-platform.

**Comment by dcoeurjo** [comment]
👌 If you want, I can set up continuous integration scripts with travis-ci (macOS & linux, various compilers).. I did that several times

**Comment by nmwsharp** [comment]
Ok, as best I can tell, as of 4327a8697e9e5f9a99cd61bd176faaea5e2d4c7c, both polyscope and the geometry-central dependency should be building happily on both recent GCC & Clang.

And thanks for the offer! I definitely want to set up CI soon, so I may ask for advice. I'm still dreaming of finding some service that will let me set up all of Linux/OSX/Windows simultaneously.

**Comment by dcoeurjo** [comment]
Yeah.. for dgtal.org, I use Travis for Mac/Linux and appveyor for Windows but a bit painful because scripts are really different. 

If you activate Travis in you repo, I can definitely help you with the scripts
