### ISSUE TITLE
Dependencies for library `glfw` may be missing from a default Ubuntu installation

### ISSUE THREAD

**Issue by TianweiOwenLi** [nmwsharp/polyscope#198]
Dear developers, 

When I was attempting to build `Polyscope` on my `Ubuntu 22.04.2` system for my project, it appeared to me that the libary `glfw`, which polyscope itself depends on, had missing dependencies. Specifically, the followings have to be installed via `apt` before polyscope successfully builds: 
```
libx11-dev
libxrandr-dev
libxinerama-dev
libxcursor-dev
libxi-dev
libglew-dev
```
The first four of these missing dependencies were straightforward to locate, but the last two missing dependencies produced some unhelpful error messages, telling me that I had missing header files `/usr/include/X11/extensions/XInput2.h` and  `/use/include/X11/extensions/XInput2.h`. I believe that neither of these comes with a default `Ubuntu` installation, and it would be rather difficult for an inexperienced user to figure out that what they needed were actually `libxi-dev` and `libglew-dev`. 

Is it possible to include these dependencies somewhere to the build process, so that other Linux users can build this project with less hassle? I would appreciate any feedback on this issue!

**Comment by nmwsharp** [comment]
Hi! Thanks for reporting this.

I don't know of any way to automatically install these libraries as part of the Cmake build process (and I don't think it's a good idea for cmake to go around installing system packages automatically regardless 😄 ). There is a list of expected dependencies in the docs here http://polyscope.run/building/#dependencies, would those have helped?

Of course I do understand that tracking down mysterious necessary packages is not fun. I'm not sure how else to make this more clear for users. If you have any concrete suggestions I'm all ears!

**Comment by TianweiOwenLi** [comment]
Thanks for the information! I had a look at the documentation and noticed that it does include all dependencies that I mentioned, so now I believe that nothing is missing :D 

(For some reason I completely missed the link to `Polyscope`'s documentation despite it being written in heading level 1 at the very top of the projects' `README.md`......I believe this issue can be closed now)
