### ISSUE TITLE
Call to undefined function in shader program

### ISSUE THREAD

**Issue by Q-Minh** [nmwsharp/polyscope#202]
Hi, running polyscope and trying to use the gizmos feature now results in the error:
```
Program info log: 
Fragment info
-------------
0(58) : error C3002: call to undefined function "bool rayCylinderIntersection(vec3, vec3, vec3, vec3, float, float, vec3, vec3);"
```
Looking at the recent commits, I see that [this one](https://github.com/nmwsharp/polyscope/commit/3c7c01496191d8b1aa0d86d15ec2bce2afdfe2c6) has modified the signature of the aforementioned function. Can anyone confirm that the change had side-effects in other environments than mine?

**Comment by nmwsharp** [comment]
Hi, thanks for reporting this!

It was a bug in the library introduced by a recent commit as you noticed. It should now be fixed. (Note that the current version of the library is a major overhaul with many changes, not just this one.)

I'm closing this assuming it's fixed. Please reopen if not.
