### ISSUE TITLE
Cannot use the slice plane (crash when using "Add Plane" )

### ISSUE THREAD

**Issue by Dong-He** [nmwsharp/polyscope#204]
Dear developers,

Thanks for the new version on the radius of the varied node which is much helpful to my work. A little bug in the new version is that I cannot use the slice plane (this is fine in old versions). When I hit the button "add plane", it jumps to the pic below with the error code

0(58) : error C3002: call to undefined function "bool rayCylinderIntersection(vec3, vec3, vec3, vec3, float, float, vec3, vec3);"

![image](https://user-images.githubusercontent.com/23613273/227421921-5aa3ae79-9f9a-4ed0-a6cc-cfcf93178948.png)
![image](https://user-images.githubusercontent.com/23613273/227422023-14aa060b-9626-48b0-9f30-71ae0fc8aa1d.png)

**Comment by nmwsharp** [comment]
Hi, thank you for reporting this!

It was a bug in the library. It should be fixed in the latest version. (Note that the latest version is a major update which contains many changes).

I'm closing this for now assuming it's fixed, please reopen if not.

**Comment by ayoubelhach** [comment]
Hi Nicolas! It seems there is still this bug when i first extract a level set from a sclar function on vertices of a  terahedral mesh, and after i add a slice plane it crashs.
