### ISSUE TITLE
Polyscope OpenGL Error! Type: Invalid operation

### ISSUE THREAD

**Issue by xarthurx** [nmwsharp/polyscope#213]
I compiled a program that runs without any problem on two of my machines.
But when I send the whole package (all `dll`, `exe`) to my friends' machine (details below) and run there, I got this error:

![image](https://user-images.githubusercontent.com/1921878/230644236-1d196763-99ae-46ca-96cb-c092d6988516.png)

```
[polyscope] Backend: openGL3_glfw -- Loaded openGL version: 3.3 NVIDIA 531.41
[polyscope] Polyscope OpenGL Error! Type: Invalid operation
[polyscope] [EXCEPTION] OpenGl error occurred. Text: Invalid operation
```

OS: Windows 10
Graphic Card: 2080Ti

The machine doesn't have any development environment. And since I don't encounter this issue, it is very hard to debug...

@nmwsharp  Do you have any clue what might be the cause?

I guess this is different from https://github.com/nmwsharp/polyscope/issues/143

**Comment by nmwsharp** [comment]
Unfortunately these are also very hard for me to debug these without the machine at hand!

If you set `options::errorsThrowExceptions = true` and `options::enableRenderErrorChecks=true`, then you should at least be able to get an exception and a stack trace right after the first operation that fails, which would be a starting point for debugging See: https://polyscope.run/basics/program_options/#render-error-checks
