### ISSUE TITLE
Use of C-style arrays

### ISSUE THREAD

**Issue by keenancrane** [nmwsharp/polyscope#22]
Use of C99 arrays can cause problems with compilation (e.g., when using -pedantic and -Werror in clang).

The only example I've run into so far is

```
template <typename T>
std::string AffineRemapper<T>::printBounds() {
  size_t bSize = 50;
  char b[bSize];
  snprintf(b, bSize, "[%6.2e, %6.2e]", minVal, maxVal);
  return std::string(b);
}
```

which can be modernized to

```
template <typename T>
std::string AffineRemapper<T>::printBounds() {
  const size_t bSize = 50;
  std::array<char,bSize> b;
  snprintf(b.data(), bSize, "[%6.2e, %6.2e]", minVal, maxVal);
  return std::string(b.data());
}
```

(Though there may be others.)

**Comment by nmwsharp** [comment]
Fixed in b201c3d41547ba8d062bd6b1fc26ef57ec548fb4. I believe that was the only instance; `-pedantic` passes on my machine now. Thanks!
