### ISSUE TITLE
Enable GLFW error console printing via verbosity option

### ISSUE THREAD

**Issue by Q-Minh** [nmwsharp/polyscope#226]
Hey Nic, it's often happened to me on Windows that I constantly get these GLFW errors, which do not affect my use cases:
```
$ GLFW emitted error: WGL: Failed to make context current: The handle is invalid.
$ GLFW emitted error: WGL: Failed to make context current: The requested transformation operation is not supported.
```
Is it possible to just make a slight change [here](https://github.com/nmwsharp/polyscope/blob/6c1c490a32bdf3ac99e89bf240b65316d4fd7787/src/render/opengl/gl_engine.cpp#L2164) to allow us to silence these console prints by simply setting the `verbosity` to `0`?
This could potentially be as simple as:
```
auto error_print_callback = [](int error, const char* description) {
    if (options::verbosity > 0) {
        std::cerr << "GLFW emitted error: " << description << std::endl;
    }
};
```
Thanks again, Polyscope is so useful!

**Comment by nmwsharp** [comment]
Good call, I never see these as a non-windows user. I just made the change exactly as you suggested in 3f86f5886d5c9bd1b978285aee105798efb85391. Please reopen if it doesn't look right.

(Side-note, I wonder if any of these errors are actually problems.... it would be good to track down where they are coming from at some point...)

**Comment by Q-Minh** [comment]
You're right, I should take time to track down the source of these error messages and provide you with more useful info, hopefully very soon.

**Comment by nmwsharp** [comment]
Heads-up, others were also seeing these errors. After some digging it seems like it's related to an alleged integrated graphics driver bug vsync. https://github.com/nmwsharp/polyscope/issues/329#issuecomment-2634073121 should fix it in the default configuration.
