### ISSUE TITLE
addQuantity does not work as advertised

### ISSUE THREAD

**Issue by keenancrane** [nmwsharp/polyscope#23]
The snippet on the landing shows these lines of code

```
// Add a scalar and a vector function to the mesh
polyscope::getSurfaceMesh("my mesh")->addQuantity("my_scalar", scalarQuantity);
polyscope::getSurfaceMesh("my mesh")->addQuantity("my_vector", vectorQuantity);
```

but should really be something like `addVertexScalarQuantity` or `addFaceVectorQuantity`, etc.  (This can cause confusion when trying out polyscope for the first time.)

**Comment by nmwsharp** [comment]
Fixed in fd37b37a0010291960796f3069cbe8e7cfbe9a98. Thanks!
