### ISSUE TITLE
Help! The directory "glfw" in the  subdirectory"deps" is empty

### ISSUE THREAD

**Issue by NoError404** [nmwsharp/polyscope#248]
The directory "glfw" in the  subdirectory"deps" is empty.
Every time, I run cmake ../ in build directory. The WLS terminal shows 
![image](https://github.com/nmwsharp/polyscope/assets/32030695/219f4fd2-3414-4b5e-8ee6-73c76b2b2f1c)
I'm new in sourecode project.

**Comment by ymclsh** [comment]
@NoError404  hello, I met the same issue, how did you solve it? Thanks.

**Comment by NoError404** [comment]
First，u  may download the source code of glfw, and put those code into the directory 'deps'. Then to compile them.

**Comment by NoError404** [comment]
@ymclsh First，u may download the source code of glfw, and put those code into the directory 'deps'. Then to compile them. U may google the way to compile the glfw.

**Comment by ymclsh** [comment]
@NoError404 Thank you so much.

**Comment by nmwsharp** [comment]
FYI, this problem probably stems from failing to clone submodules.

GLFW (and other dependencies) are managed as [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). Submodules allow a git repository to have subdirectories which are themselves references to other separate git repositories. However, it take extra commands to ensure that these subdirectories are populated. 

If you clone the project like `git clone --recursive ...` it should automatically download all of the submodules, but if you forget the `--recursive` flag you will be left with empty subdirectories. If you forgot the flag initially, you can later run `git submodule update --init --recursive` to download them.

If you are using a GUI or IDE for git, look around for a button or option that says something about submodules.
