### ISSUE TITLE
Volume Grid Marching Cube gives a rotated result

### ISSUE THREAD

**Issue by avaxman** [nmwsharp/polyscope#253]
<img width="1631" alt="Screenshot 2024-01-30 at 16 08 38" src="https://github.com/nmwsharp/polyscope/assets/8985720/6cb1125a-c771-4a82-a0ed-14d8bdb585dc">
<img width="1557" alt="Screenshot 2024-01-30 at 16 05 47" src="https://github.com/nmwsharp/polyscope/assets/8985720/650764d2-2712-4d0c-ba0d-81f504bb7fd2">
I run the following pretty classic RBF reconstruction in Python. The Volume grid function seems correct, but the result isosurface is correct up to rotation. I tried both explicit grid and callback, and they both give the same rotation. Since the scalar function is fine, I think something is wrong with the marching cubes. 

(change the data folder to accommodate where you put the input).
[RBF.zip](https://github.com/nmwsharp/polyscope/files/14100976/RBF.zip)
<img width="1667" alt="Screenshot 2024-01-30 at 16 08 46" src="https://github.com/nmwsharp/polyscope/assets/8985720/c39c0820-660b-442e-a2f4-ea686fe79be7">

**Comment by nmwsharp** [comment]
Thank you very much for filing this! You were exactly right, there was a coordinate-ordering bug that I had totally missed.

Fixed in 5d0bb5ea8cdaac07264cf2c3dd17c7b7b7f1cb78. Will push a new version of the python lib to incorprate this and other fixes soon.
