### ISSUE TITLE
allowReplacement not exposed through public interface

### ISSUE THREAD

**Issue by keenancrane** [nmwsharp/polyscope#26]
Trying to set an existing quantity with `add*Quantity` yields an error message that cannot be resolved by setting the requested option.  For instance, running `SurfaceMesh::addVertexScalarQuantity` twice yields an error message

```[ERROR] Tried to add quantity with name: [quantity], but a quantity with that name already exists on the structure [mesh]. Use the allowReplacement option like addQuantity(..., true) to replace.```

but there is no way to pass this option through `addVertexScalarQuantity`.

**Comment by nmwsharp** [comment]
This one is already "fixed" in master if you update to latest via 5ef044b8f3f058dfee3b3b0d18864cc3c012b903. That just changes the default policy to allow replacement.

The initial plan was that every single `add___Quantity()` function would have an optional `allowReplacement` bool, but on reflection I really don't think that's worthy of a parameter in every method signature. The idea was to catch bugs where one accidentally overwrites a quantity with the same name, but I think it's more of an annoyance that a convenience.
