### ISSUE TITLE
The imgui cmake mac fix breaks on -Werror=... flags

### ISSUE THREAD

**Issue by tzh1043** [nmwsharp/polyscope#32]
The added line to `deps/imgui/CMakeLists.txt`

    string(REPLACE " -Werror" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

breaks builds when the flags contain `-Wall -Werror=return-type`, this gets mangled to `-Wall=return-type`

Suggested fix:

    string(REPLACE "-Werror=" "-Wno-error=" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
    string(REPLACE " -Werror" "" CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")

**Comment by nmwsharp** [comment]
Ah, this makes sense. Thanks for the report!

Just pushed 99d008252191671da2c3caed49f8fb3dc81f652a, which changes it to:
```cmake
if ("${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang" OR "${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error")
endif()
```
appending `Wno-error` last should override any previous instances of `Werror`, and seems less error prone than string replacements.

Please reopen if you encounter other problems or this fix doesn't work.
