### ISSUE TITLE
updateVertexPositions does not update wireframe

### ISSUE THREAD

**Issue by keenancrane** [nmwsharp/polyscope#34]
Just calling `updateVertexPositions` does not seem to properly update the GL buffers storing the data for wireframe rendering.  Instead, the original wireframe gets drawn (and clipped against the silhouette of the new geometry?).  Here's an example:

![bad_wireframe](https://user-images.githubusercontent.com/3604525/63636677-636ff900-c640-11e9-9666-42e26657b8af.jpg)

**Comment by nmwsharp** [comment]
Thanks for the report, should be fixed in 097f17cd01c40e26c24ab539732988cc83956797!
