### ISSUE TITLE
Permutation expected size is off by one

### ISSUE THREAD

**Issue by MarkGillespie** [nmwsharp/polyscope#37]
In the permutation setter functions (e.g. `setEdgePermutation`), you set the size of the index space to be the maximum entry of the permutation. But it appears that the indices in the permutation are supposed to be 0-indexed, which means that the maximum entry is actually 1 less than the desired size

**Comment by nmwsharp** [comment]
Ah, good catch! Thanks for the report.

I'll fix this as soon as I get some engineering time, or happy to accept a pull request if you've already fixed it somewhere.

**Comment by nmwsharp** [comment]
Fixed in https://github.com/nmwsharp/polyscope/pull/38
