### ISSUE TITLE
Volume rendering?

### ISSUE THREAD

**Issue by NAThompson** [nmwsharp/polyscope#40]
Forgive me if I have not read the documentation thoroughly, but is there a canned subroutine for [volume rendering](https://graphics.stanford.edu/papers/volume-cga88/)?

**Comment by nmwsharp** [comment]
Right now there's no built-in functionality for volume rendering, though we hope to incorporate it in the near future!

**Comment by NAThompson** [comment]
Ok, cool! BTW, great project, really well designed and usable.

**Comment by nmwsharp** [comment]
Thank you! Glad it's useful :)
