### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by pauljurczak** [nmwsharp/polyscope#42]
Building polyscope on Ubuntu 18.04.3 with cmake VERSION 3.16.2 according to instructions at http://polyscope.run/building/ produces this error:
```
[cmake] CMake Error at CMakeLists.txt:13 (add_subdirectory):
[cmake]   add_subdirectory not given a binary directory but the given source
[cmake]   directory "/home/paul/libraries/polyscope" is not a subdirectory of
[cmake]   "/home/paul/st/hello/src".  When specifying an out-of-tree source a binary
[cmake]   directory must be explicitly specified.
```
I suggest changing 
`add_subdirectory("polyscope")` 
to 
`add_subdirectory("polyscope" "polyscope")` 
in instructions at http://polyscope.run/building/ 

AFAIK, it has the same semantics, but may be more tolerant to out-of-tree location of polyscope files.

**Comment by nmwsharp** [comment]
Ah, this issue makes sense. Thanks!

I think the more idiomatic solution might be to support `find_package` for out-of-tree inclusion, but I need to read up on cmake to be more confident about implementing that. 

In the meantime this is a pragmatic fix of course. I'll look in to this more soon.

**Comment by nmwsharp** [comment]
OK! This does seem like a reasonable easy fix for out-of-tree builds.

I'll add the following line to the docs:
> If you place polyscope outside of your project’s source tree, you may need add_subdirectory("path/to/polyscope" "polyscope") to also set a library build directory.

which will be updated soon in an upcoming release. Hopefully some day soon I can sort out `find_package`.

Thanks for pointing this out!
