### ISSUE TITLE
Issue with the raycaster for point cloud color quantities

### ISSUE THREAD

**Issue by dcoeurjo** [nmwsharp/polyscope#49]
Nice but strange issue when attaching a color quantity to a point cloud: 

![Capture d’écran 2020-03-28 à 10 11 28](https://user-images.githubusercontent.com/700165/77819712-322b4000-70dd-11ea-98d2-b50496d82683.png)

(I'm using the latest version of polyscope)

**Comment by dcoeurjo** [comment]
(top right: points are close on purpose)

**Comment by nmwsharp** [comment]
Uh oh, that doesn't look great, haven't seen that before.

I can't immediately reproduce the issue; do you always get these artifacts or only in certain situations?

**Comment by dcoeurjo** [comment]
👌 
let me investigate a bit..

**Comment by nmwsharp** [comment]
Closing for now. Feel free to reopen with more info!
