### ISSUE TITLE
Color Quantities on Curve Networks don't render colors (Python API)

### ISSUE THREAD

**Issue by ranahanocka** [nmwsharp/polyscope#56]
Hi @nmwsharp ,

Thank you for this excellent package!

I was not able to get the colors to render in the curve network example. 

As written in the [example](https://polyscope.run/py/structures/curve_network/color_quantities/) in the documentation, I ran the exact code (with the addition of ps.init()) 
```
import numpy as np
import polyscope as ps

# register a curve network
N_node = 100
N_edge = 250
nodes = np.random.rand(N_node, 3)
edges = np.random.randint(0, N_node, size=(N_edge,2))
ps_net = ps.register_curve_network("my network", nodes, edges)

# visualize some random colors per-node
# vals_node = np.random.rand(N_node, 3)
# ps_net.add_color_quantity("rand vals", vals_node)

# visualize some random colors per-edge
vals_edge = np.random.rand(N_edge, 3)
ps_net.add_color_quantity("rand vals2", vals_edge, defined_on='edges')


# view the network with all of these quantities
ps.init()
ps.show()
```

and the result looks like this: 
![image](https://user-images.githubusercontent.com/14359648/80368671-c122a800-8895-11ea-9093-be7e88c47081.png)

I am using the Python API (Python 3.6.8), Ubuntu 18.04. I installed the pre-compiled wheels via `python -m pip install polyscope`.

Did I miss something?

Thanks!
-Rana

**Comment by bbrrck** [comment]
You need to enable the quantity. In code that would be:
```ps_net.add_color_quantity("rand vals2", vals_edge, defined_on='edges', enabled=True)```
You can also do this in the gui, there is a checkbox that appears if you click on the name of the quantity.

**Comment by ranahanocka** [comment]
Perfect. Thanks @bbrrck !
