### ISSUE TITLE
animation support??

### ISSUE THREAD

**Issue by JianqiangDing** [nmwsharp/polyscope#59]
Hi, does the polyscope supports animating now? for instance, how could I use polyscope to check the procedure of the points' removing for a given point cloud continually with only one window?

**Comment by JianqiangDing** [comment]
Hi, I've checked the source code of the project, it seems that polyscope doesn't provide single point removing API for a given point cloud, you handle the point cloud as a whole structure which stored in a map and sort them by the name of the structure. so my question is, is that efficient to construct a single point as a structure and then remove it one by one from the point cloud?  any suggestions would be helpful.

**Comment by nmwsharp** [comment]
Hi, thanks for checking out the project! Your understanding is correct, there is no support in the API for adding/removing points from an existing point cloud.

The best workaround I can suggest is to re-register a new point cloud with the same name, but one fewer point. Of course, this is a less efficient method, but it might scale fine to decently-large point clouds. 

Polyscope generally does not have much animation support, but you can update the scene every frame using the [user callback](http://polyscope.run/features/user_callback/) (for example, registering an updated point cloud).

**Comment by JianqiangDing** [comment]
thanks for your response, really helpful. you are right, I'll try the method in your way.
you may close the issue now. by the way, really useful work for CG!!!

**Comment by nmwsharp** [comment]
thanks, good luck!
