### ISSUE TITLE
Shader  issue with the Curve Network structure

### ISSUE THREAD

**Issue by dcoeurjo** [nmwsharp/polyscope#60]
I'm have a weird issue with Curve Network: the embedding of nodes seems to be wrong.

![output](https://user-images.githubusercontent.com/700165/81927882-add94180-95e4-11ea-8ec4-6bfb7eb1ace3.gif)

My test: I create a simple curve network with small segments starting at mesh vertices and going inside the mesh. What we see in the video is just the first nodes. 
The issue is that the curve tips should coincide with the mesh vertices (which is not the case). 

If you look at the coordinates (selection windows), they are exactly the same. It looks like it's only a draw issue.

(tested on macOs)

**Comment by dcoeurjo** [comment]
![output2](https://user-images.githubusercontent.com/700165/81929501-67391680-95e7-11ea-8c04-1e3a19a84a96.gif)

weirder and weirder... Two networks, ({p<->p'=p + delta*n} ,  {p'<->p' + delta*n}) and the extremities have te same coordinates (internally) but the draw is buggy...

**Comment by nmwsharp** [comment]
Hmmm, this is very odd.

Perhaps is autocenter/autoscale structures enabled? If the structures have slightly different extents, they could be getting transformed differently causing them to not align.

**Comment by dcoeurjo** [comment]
yeah! good guess.. removing the `autocenterStructure` solves the issue.
Thx.
