### ISSUE TITLE
Add faux transparency 

### ISSUE THREAD

**Issue by keenancrane** [nmwsharp/polyscope#64]
There are a lot of tricks for rendering transparency; this one is particularly friendly to the rasterization pipeline and could work well in Polyscope (also because it nicely highlights contours): 

https://observablehq.com/@rreusser/faking-transparency-for-3d-surfaces

“Cartoon edges” might be replaced with simple edge based silhouettes (i.e., compare the sign of the dot product of the normal with the eye for the 2+ triangles touching an edge), since the former works well only for well-tessellated surfaces.

**Comment by nmwsharp** [comment]
(closing old issues)

Transparency is now very well supported! We have both simple average blending and depth peeling. Cheers!
