### ISSUE TITLE
OpenGL errors from `generateTextureBufferMultisample()` in WSL

### ISSUE THREAD

**Issue by nmwsharp** [nmwsharp/polyscope#70]
It seems like some machines which claim to support openGL 3.3 core are erroring out on the multisample textures. Perhaps we accidentally used something which is not valid in core 3.3?

**Comment by bbrrck** [comment]
I'm having the same problem on a freshly installed Ubuntu 20.

**Comment by josefgraus** [comment]
I don't know for certain, but WSL2 is going through some fairly significant changes to driver support for graphics devices. Every week or so the latest Windows Insider Preview will alternate in fixing and then break CUDA support. It's pretty frustrating.

Not sure if this is the issue you're facing, but worth a look at insider program?

**Comment by nmwsharp** [comment]
Thank for the info all!

@bbrrck which graphics drivers are you using? I've seen some issues like this which surface on Nouveau but not NVidia drivers. I'm guessing Nouveau since you mention fresh install?

I'm considering a simpler solution for the next version, which is just to cut out the multisampled buffers. It's not really crucial, since it's only used for visual polish via anti-aliasing (MSAA). And SSAA is a better option anyway for one-off pretty screenshots, since it properly antialiases the raycasted spheres/cylinders/arrows.

I try to stick with a "works anywhere" philosophy with Polyscope whenever possible, and since this seems to be a blocker for places where Polyscope would already work, better to just cut it until we can be sure.

**Comment by bbrrck** [comment]
@nmwsharp I had the issue on a laptop with an AMD processor (Ryzen 4750) with an integrated graphics card, using mesa drivers that come with Ubuntu. OpenGL version was 3.3 according to `glxinfo`.

I have since installed drivers from [Oibaf's PPA](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) (OpenGL 4.6) and polyscope worked fine with those.

**Comment by nmwsharp** [comment]
FYI multisampling is removed in 59937d3e47083bbd2c74aa23364cef2683b291ca. Hopefully this resolves these build issues.

**Comment by nmwsharp** [comment]
(closing for now, please reopen if anyone is still seeing this)
