### ISSUE TITLE
different behavior when being called for the second time [python]

### ISSUE THREAD

**Issue by ranahanocka** [nmwsharp/polyscope#73]
Hi,

I wrote a minimal script to describe the issue I am experiencing. From a high level, if I iterate through a series of objects to render, some type of meta-data is stored, and the results are different depending on what order the objects are rendered in. Even though I set `ps.set_use_prefs_file(False)` and `ps.set_always_redraw(True)` for good measure, the results still vary.

For example, below, I show how setting the 'z_up' direction once, and then setting it to 'y_up' will result in the same output. If you change the order, the outputs will be different than previously, but still each render is identical. Any clues as to why this is happening?

```bash
import numpy as np


import polyscope as ps
ps.set_use_prefs_file(False)
ps.set_always_redraw(True)
ps.init()


np.random.seed(1)
points = np.random.rand(4, 3)
vals = np.random.rand(4, 3)


ps.set_up_dir('z_up')
ps_cloud = ps.register_point_cloud('points', points, enabled=True, radius=0.08)
ps_cloud.add_color_quantity("rand colors", vals, enabled=True)
ps.set_navigation_style("planar")
ps.screenshot(filename='/home/rana/code/sandbox/points_z.png')

ps.set_up_dir('y_up')
ps_cloud = ps.register_point_cloud('points', points, enabled=True, radius=0.08)
ps_cloud.add_color_quantity("rand colors", vals, enabled=True)
ps.set_navigation_style("planar")
ps.screenshot(filename='/home/rana/code/sandbox/points_y.png')
```

**Comment by nmwsharp** [comment]
Hi, 

Thanks for reporting this, there's definitely a bug here :exploding_head: 

I looked in to this for a few minutes, and it's not even obvious to me what's going on... something is going very wrong with the rotations related to the up-direction, but have no idea what.

Even this more-minimal program yields unexpected behavior, with the camera rotated at a funny angle (...and the menu item not updating?!?)

```python
import polyscope as ps
ps.init()
ps.show()
ps.set_up_dir('z_up')
ps.show()
```

I'm going to have to debug a bit more deeply to figure this out; I'll do that as soon as I can and post back here.

**Comment by ranahanocka** [comment]
Thanks for letting me know! I am not sure if this is related to the other problem that I mentioned, which is that the meta-information is somehow preserved when rendering multiple objects sequentially. 
I noticed that when viewing objects one after another using the UI, if I hit "reset view" , then this does seem to re-center each object. 

Is it possible to call this from the python API?

**Comment by nmwsharp** [comment]
OK! I think I have this all sorted out. There were a few small overlapping issues related to view/camera management (including that the view was not being reset in a consistent way, as you mentioned). Thanks for the report!

As of these commits (961a7227bf3aca1cfe119dcab6758263bbc2ee44,   nmwsharp/polyscope-py@32ebf815d9b2894dd1d453af58391f1fb7577a38), everything should work as expected. Let me know if you see further issues! I also added a binding for `reset_camera_to_home_view()`.

Assuming all the CI tests/builds go through as expected, I'll cut a version and push a new build to pypi & conda tonight; they should available by tomorrow at least. 

(This update will also include a few other small quality-of-life fixes I've had sitting around, like supporting negative-axis up directions, and allowing you to kill the python app with ctrl-c, and fixing python support for relative paths in filenames such in `screenshot()`)

**Comment by ranahanocka** [comment]
Amazing!! Really looking forward to all these fixes :)

**Comment by ranahanocka** [comment]
So I grabbed the latest version, and there's definitely something working better with those rotations now ! :smile: 
However, I am still experiencing an issue with some stored meta-data when iterating through different objects to render. In particular, I think something is happening with the scale, even though I tried the `reset_camera_to_home_view()`. Another thing which might be related, I think I noticed that sometimes the images will contain some pieces of the the previous object I rendered?

Here is another script which demonstrates that (I basically just multiply the first point set by 5x, to make it much bigger than the next one I render)

```bash
import numpy as np


import polyscope as ps
ps.set_use_prefs_file(False)
ps.set_always_redraw(True)
ps.init()


np.random.seed(1)
points = np.random.rand(4, 3)
vals = np.random.rand(4, 3)


ps_cloud = ps.register_point_cloud('points', 5*points, enabled=True, radius=0.08)
ps_cloud.add_color_quantity("rand colors", vals, enabled=True)
ps.screenshot(filename='/home/rana/code/sandbox/points_z.png')

ps.reset_camera_to_home_view()
ps_cloud = ps.register_point_cloud('points', points, enabled=True, radius=0.08)
ps_cloud.add_color_quantity("rand colors", vals, enabled=True)
ps.screenshot(filename='/home/rana/code/sandbox/points_y.png')
```

**Comment by nmwsharp** [comment]
If you move the `reset_camera_to_home_view()` to after you register the new point cloud (one line below the current location), does it do what you want? The "home view" is a function of current data in the scene---it's automatically computed from the bounding box of all registered structures to ensure everything is visible. So here, you probably want to call it after the new data has been added.

In retrospect, the name "reset_camera_to_home_view" is kinda confusing, it doesn't make it obvious that it's a function of the content in the scene.... I can add a note to the docs about that, might even change the name of the function.


> the images will contain some pieces of the the previous object

Hopefully this is just an issue of the camera being in the wrong spot, but if you're still seeing it please let me know!

**Comment by ranahanocka** [comment]
Yes -- that works like a charm. Thanks!!
Right, now that you mention it I get why it has to be called after the structures are registered.

**Comment by nmwsharp** [comment]
Ok, new versions should be available on conda and pip now; closing this issue. Feel free to reopen if needed!
