### ISSUE TITLE
Carsh on try to close GUI window

### ISSUE THREAD

**Issue by MasoudBNJ** [nmwsharp/polyscope#74]
When I try to close polyscope UI (glfw screen), the program displays 'not responding' and then crashes.
I'm running it on python from Anaconda Powershell Prompt (Windows 10).
Also is there any shortcuts for closing the window properly?? (Other than 'X' button on windows)

**Comment by nmwsharp** [comment]
Hi!

I suspect what you describe as a crash may actually be the program working as-expected.

When you click to close the window, what actually happens is that Polyscope returns control to your script to continue executing, and the Polyscope window just sits there waiting for another call to `show()` from your code.

If you are running Polyscope in Python from the interactive prompt, this means that prompt just sits there, waiting for your next input. So in-appearance, the Polyscope Window is stuck, whereas really its just waiting for you to call `show()` again (or exit the interactive session).


(I realize that this can be confusing.... perhaps I should change this behavior, though I'm not totally sure to what.)

**Comment by nmwsharp** [comment]
^^^^If that doesn't match what you're seeing, can you describe in more detail?

**Comment by MasoudBNJ** [comment]
Hi!
Thank you very much :))
You're right and it works as expected. Actually, I had not noticed that when I click the close button on Polyscope windows the interactive python interface allows me to write new codes (and again call `show()`).
Also when I run a Polyscope code through `python example.py` and I press the close button it closes the app properly.
