### ISSUE TITLE
Add an example interfacing with OpenMesh

### ISSUE THREAD

**Issue by nmwsharp** [nmwsharp/polyscope#77]
https://www.graphics.rwth-aachen.de/software/openmesh/

Add an "integration" example similar to the existing ones (e.g. http://polyscope.run/integrations/libIGL/) for OpenMesh. If necessary, we can also add additional template adaptors to Polyscope to make this interface less painful.

**Comment by vijaiaeroastro** [comment]
Hey @nmwsharp. Perhaps this can serve as an example. I do not use any adaptors and simply convert the data though. So i am not really sure how useful it is 😃 

https://github.com/vijaiaeroastro/openMeshPolyscope
