### ISSUE TITLE
imgui doesn't link to its dependencies

### ISSUE THREAD

**Issue by evouga** [nmwsharp/polyscope#86]
The imgui library (at least in GLFW backend mode) requires glfw and glad as dependencies. But they're missing from `deps/imgui/CMakeLists.txt`.

This means that a completely blank polyscope project does not build. I fixed the problem by adding
````
target_link_libraries(imgui PRIVATE glfw glad)
````
at line 24.

Note that this problem will not arise in a project that uses both polyscope and imgui features (since the root project will pull in glfw and glad on its own), but occurs whenever the root project does not directly link to glfw itself.

**Comment by nmwsharp** [comment]
Ah, that makes sense. Thanks for reporting!

Fixed in 679ddfee1032aa8b3b0836f2abf603a7bdeb3edc.
